import React, { useState } from 'react';
import {
  Check,
  Copy,
  Download,
  Sparkles,
  RefreshCw,
  CheckCircle2,
  Bot
} from 'lucide-react';
import { GherkinEditor } from './GherkinEditor';

interface DiffViewerProps {
  originalGherkin: string;
  improvedGherkin: string;
  improvementsCount: number;
  recommendations: string[];
  fileName?: string;
  onApplyImproved?: () => void;
  isReanalyzing?: boolean;
}

export const DiffViewer: React.FC<DiffViewerProps> = ({
  originalGherkin,
  improvedGherkin,
  improvementsCount,
  recommendations,
  fileName = 'feature.feature',
  onApplyImproved,
  isReanalyzing
}) => {
  const [copied, setCopied] = useState(false);

  const handleCopyImproved = () => {
    navigator.clipboard.writeText(improvedGherkin);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadImproved = () => {
    const blob = new Blob([improvedGherkin], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = fileName.replace('.feature', '_improved.feature');
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">
      
      {/* Header Banner */}
      <div className="p-5 rounded-2xl bg-gradient-to-r from-slate-900 via-indigo-950 to-slate-900 text-white flex flex-col md:flex-row items-start md:items-center justify-between gap-4 shadow-md">
        <div className="space-y-1">
          <div className="flex items-center gap-2">
            <span className="px-2.5 py-0.5 rounded-full text-[11px] font-bold bg-amber-500/20 text-amber-300 border border-amber-500/30 uppercase tracking-wider flex items-center gap-1">
              <Bot className="w-3.5 h-3.5" />
              AI Engine + Framework Auto-Fixer
            </span>
            <span className="text-xs text-emerald-400 font-bold flex items-center gap-1">
              <Sparkles className="w-3.5 h-3.5" />
              {improvementsCount} Recommended Fixes Applied
            </span>
          </div>
          <h3 className="text-lg font-bold">Your Feature File vs. AI Enhanced Version</h3>
          <p className="text-xs text-slate-300">
            Automatically enhanced with missing failure scenarios, clear Given/When/Then steps, and exact assertions generated by the AI Engine &amp; Quality Framework.
          </p>
        </div>

        <div className="flex flex-wrap items-center gap-2.5">
          <button
            onClick={handleCopyImproved}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-slate-800 hover:bg-slate-700 text-xs font-semibold text-white border border-slate-700 transition"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
            <span>{copied ? 'Copied' : 'Copy Improved'}</span>
          </button>

          <button
            onClick={handleDownloadImproved}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-slate-800 hover:bg-slate-700 text-xs font-semibold text-white border border-slate-700 transition"
          >
            <Download className="w-3.5 h-3.5" />
            <span>Download .feature</span>
          </button>

          {onApplyImproved && (
            <button
              onClick={onApplyImproved}
              disabled={isReanalyzing}
              className="flex items-center gap-1.5 px-4 py-1.5 rounded-xl bg-emerald-600 hover:bg-emerald-500 text-xs font-bold text-white shadow-sm transition active:scale-95"
            >
              {isReanalyzing ? (
                <RefreshCw className="w-3.5 h-3.5 animate-spin" />
              ) : (
                <CheckCircle2 className="w-3.5 h-3.5" />
              )}
              <span>Re-Check with Improved Version</span>
            </button>
          )}
        </div>
      </div>

      {/* Side-by-Side Code View */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        
        {/* Original File */}
        <div className="space-y-2">
          <div className="flex items-center justify-between px-3 py-2 bg-slate-100 rounded-xl text-xs font-bold text-slate-700">
            <span>Original Uploaded Version</span>
            <span className="text-slate-500 font-mono">Before Fixes</span>
          </div>
          <GherkinEditor
            content={originalGherkin}
            readOnly={true}
            title="Original Feature"
            fileName={fileName}
          />
        </div>

        {/* Improved File */}
        <div className="space-y-2">
          <div className="flex items-center justify-between px-3 py-2 bg-emerald-100/70 border border-emerald-200 rounded-xl text-xs font-bold text-emerald-900">
            <span className="flex items-center gap-1.5">
              <Sparkles className="w-3.5 h-3.5 text-emerald-600" />
              AI Enhanced Gherkin Version
            </span>
            <span className="text-emerald-700 font-mono">Ready to Run</span>
          </div>
          <GherkinEditor
            content={improvedGherkin}
            readOnly={true}
            title="Improved Feature"
            fileName={fileName.replace('.feature', '_improved.feature')}
          />
        </div>

      </div>

      {/* Recommended Practices List */}
      {recommendations && recommendations.length > 0 && (
        <div className="p-5 rounded-2xl bg-white border border-slate-200 shadow-xs space-y-3">
          <h4 className="text-sm font-bold text-slate-900 flex items-center gap-2">
            <CheckCircle2 className="w-4 h-4 text-emerald-600" />
            Key Improvements Made to Your Feature File:
          </h4>
          <ul className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-xs text-slate-600">
            {recommendations.map((rec, idx) => (
              <li key={idx} className="flex items-start gap-2 bg-slate-50 p-2.5 rounded-xl">
                <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 mt-1.5 shrink-0" />
                <span>{rec}</span>
              </li>
            ))}
          </ul>
        </div>
      )}

    </div>
  );
};
